### ISSUE TITLE
Add topics to this repo

### ISSUE THREAD

**Issue by ghost** [tdammers/Douglas-Dc3#1]
Add topics to this repo for make it more visible like this:
https://github.com/NikolaiVChr/f16
https://github.com/Octal450/MD-11

**Comment by tdammers** [comment]
I'm not actively seeking exposure here, at least for now; this is my personal fork, and while you're welcome to use it, the goal is not to grow a large user base or do a lot of maintainer work, so I won't make it more discoverable, at least not until things change on that front.
