### ISSUE TITLE
Got stuck in startup tutorial on mixture control

### ISSUE THREAD

**Issue by ghost** [tdammers/Douglas-Dc3#2]
dear Tobias,

When running the startup tutorial the mixture control is either too high or too low. Not able to continue in this tutorial.

I know how to fix this in the files DEstartup.xml, ENstartup.xml and FRstartup.xml. But I'm a beginner on GitHub. This fix would be a nice one to practice how to use GitHub.

Do I have to create a branch of main, fix in that branch and create a pull request for you to review the fix? Or...

thanks, Siebren.

**Comment by tdammers** [comment]
You may want to contact the upstream maintainer, Emmanuel Baranger, a.k.a.
Helijah; my branch mainly exists for my own needs, and those don't include
tutorials. You could of course shoot me a PR, and if it looks solid, I'll
merge it, but until I do massively more work on this aircraft and replace
most of Emmanuel's work on the FDM and systems, my fork will not be
available via FGADDON / launcher, and support will be provided on an "if I
feel like it" basis.

Cheers,

Tobias
